---
############################################################################
#        RESETEO DE PUERTOS EN EQUIPOS DE ACUERDO A PARAMETROS EN          #
#        INVENTORY         !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO         # 
############################################################################

- name: Reseteo de puertos de un router
  hosts: router-puertos
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.puerto_id }}          
          - no ip address 
          - shutdown      
      loop: "{{ puertos_parametros }}"
- name: Reseteo de puertos de un switch
  hosts: switch-puertos
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.puerto_id }}  
          - no ip address        
          - switchport  
          - shutdown              
      loop: "{{ puertos_parametros }}"