---
############################################################################
#       RESETEO DE ETHERCHANNEL EN EQUIPOS DE ACUERDO A PARAMETROS EN      # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: RESETEO DE ETHERCHANNEL CAPA 2
  hosts: equipos-etherchannel-capa2 
  gather_facts: no
  tasks:      
    - ios_config:
        lines:
          - no interface port-channel {{ item.etherchannel_numero }}    
      loop: "{{ etherchannel_capa2_parametros }}" 
    
    - ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no channel-group {{ item.etherchannel_numero }} mode active 
          - no switchport
          - shutdown
      loop: "{{ etherchannel_capa2_parametros }}"

- name: RESETEO DE ETHERCHANNEL CAPA 3
  hosts: equipos-etherchannel-capa3
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - no interface port-channel {{ item.etherchannel_numero }}

      loop: "{{ etherchannel_capa3_parametros }}"        
    - ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no channel-group {{ item.etherchannel_numero }} mode active 
          - no switchport
          - shutdown
      loop: "{{ etherchannel_capa3_parametros }}"

