---
############################################################################
#          RESETEO DE HSRP EN EQUIPOS DE ACUERDO A PARAMETROS EN           # 
#          INVENTORY     !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO           # 
############################################################################

- name:  Reseteo de un switch HSRP Activo
  hosts: equipo-hsrp-activo-switch
  gather_facts: no
  tasks: 
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - no standby {{ item.hsrp_numero }} 
      loop: "{{ hsrp_switch_activo }}"
- name: Reseteo de un switch HSRP Standby 
  hosts: equipos-hsrp-standby-switch
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - no standby {{ item.hsrp_numero }}    
      loop: "{{ hsrp_switch_standby }}"
- name: Reseteo de un router HSRP Activo
  hosts: equipo-hsrp-activo-router
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - no standby {{ item.hsrp_numero}}        
      loop: "{{ hsrp_router_activo }}"
- name: Reseteo de un router HSRP Standby
  hosts: equipos-hsrp-standby-router
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - no standby {{ item.hsrp_numero}}       
      loop: "{{ hsrp_router_standby }}"