---
############################################################################
#      RESETEO DEL BANNER MOTD EN EQUIPOS DE ACUERDO A PARAMETROS EN       # 
#      INVENTORY             !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO       # 
############################################################################

- name: Reseteo de Banner Motd
  hosts: all
  gather_facts: no
  tasks:    
    - ios_banner:
        banner: motd
        state: absent