---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: advertencia
      prompt: ¡¡¡Advertencia!!! Este Playbook BORRARA CONFIGURACIONES!!! Desea continuar? s/n
      private: no
  tasks:
    - name: Reseteo de puertos 
      include: 01-reset-configurar-puertos.yml
      vars:
        opcion: "{{ advertencia }}" 
      when: opcion == "s"
