---
########################################################################
# RESETEO DE PUERTOS DE UN ROUTER DE ACUERDO A PARAMETROS EN INVENTORY #
#             !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                  #
########################################################################
- name: RESETEAR PUERTOS ROUTER
  hosts: router
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.puerto_id }}          
          - no ip address 
          - shutdown      
      loop: "{{ puertos_parametros }}"