---
########################################################################
# RESETEO DE PUERTOS DE UN SWITCH DE ACUERDO A PARAMETROS EN INVENTORY #
#             !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                  #
########################################################################
  - name: RESETEAR PUERTOS SWITCH CAPA 3
    hosts: switch-capa3
    gather_facts: no
    tasks:     
      - ios_config:
          lines:
            - interface {{ item.puerto_id }}          
            - no ip address
            - switchport 
            - shutdown      
        loop: "{{ puertos_parametros }}"