---
- name: Reseteo de puertos 
  include: 01-reset-configurar-puertos.yml

- name: Reseteo de Etherchannel 
  include: 02-reset-etherchannel.yml

- name: Reseteo de OSPF
  include: 03-reset-ospf.yml

- name: Reseteo de Vlans 
  include: 04-reset-vlans.yml

- name: Reseteo de HSRP 
  include: 05-reset-hsrp.yml

- name: Reseteo de Usuarios
  include: 06-reset-usuarios.yml

- name: Reseteo de Banner Motd 
  include: 07-reset-banner.yml