---
- name: Backup con el comando "Show ip interface brief"
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:

    - name: Ejecutando el comando "show ip interface brief"
      ios_command:        
        commands:
          - show ip interface brief      
      register: show_ip_int_br_output

    - name: Grabar la configuracion de los equipos de red
      copy:
        content: "{{show_ip_int_br_output.stdout[0]}}"
        dest: repositorio/{{ nombre_empresa }}/backup-show_ip_int_br/{{inventory_hostname}}-sh-ip-int-br.txt 