---
- name: Obtener datos de los dispositivos y guardarlos en un formato csv
  hosts: all
  gather_facts: no
  vars:   
    info_dir: "./repositorio"
    report_file: "{{ info_dir }}/detalle-de-equipos.csv"  
  tasks:
    - name: Creando/confirmando directorio
      file:
        path: "{{ info_dir }}"
        state: directory
      run_once: yes
      delegate_to: localhost    
    - name: get IOS device facts 
      ios_facts:
        gather_subset: all    
    - name: Save device facts
      template:
        src: template/detalle-de-equipos.j2
        dest: "{{ report_file }}"
