---
- name: Backup con el comando "show run"
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:

    - name: pull device configurations
      ios_command:        
        commands:
          - show run      
      register: show_run_output

    - name: Crear directorio
      file: 
        path: ./repositorio/{{ nombre_empresa }}/backup-show_run/       
        state: directory

    - name: save device configurations
      copy:
        content: "{{show_run_output.stdout[0]}}"
        dest: repositorio/{{ nombre_empresa }}/backup-show_run/{{inventory_hostname}}-sh-run.txt 