---
- name: Obtener datos de los dispositivos y guardarlos en un formato csv
  hosts: all
  connection: local
  gather_facts: no
     
  tasks:

    - name: get IOS device facts 
      ios_facts:
        gather_subset: all  

    # - name: Crear directorio
    #   file: 
    #     path: ./repositorio/{{ nombre_empresa }}/detalles      
    #     state: directory
    #   run_once: yes
    #   delegate_to: localhost  

    - name: Save device facts
      template:
        #src: ./template/detalle-de-equipos.j2
        src: detalle-de-equipos.j2
        #dest: "{{ report_file }}"
        dest: ./repositorio/{{ nombre_empresa }}/detalle-de-equipos.csv
