---
# PARAMETROS GENERALES DE ENTORNO

# !!!PRECAUCIÓN!!! PARAMETROS QUE NO SE DEBEN MODIFICAR
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable

# PARAMETROS QUE SE DEBEN LLENAR
# En el parámetro "ansible_user" introducir el usuario principal de la red
ansible_user: esteban
# En el parámetro "ansible_password" introducir el password principal de la red
ansible_password: cisco
# En el parámetro "ansible_become_pass" introducir el password del nodo principal
ansible_become_pass: cisco
# En el parámetro "gitlab_project_id" introducir el id del proyecto de su entorno en gitlab
gitlab_project_id: 23287753
#gitlab_project_id: 29126697
# En el parámetro "gitlab_access_token" introducir el token del proyecto de su entorno en gitlab
gitlab_access_token: 3Ye2qu2WJQnzYmZW2X-G
#gitlab_access_token: Y2s5fDXk8gjj_uokooVH

# PARAMETROS GENERALES DE RED

# PARAMETROS DE OSPF NETWORK Y AREA
ospf_network: 192.168.10.0 255.255.255.0
ospf_area: 0

# PARAMETROS DE SERVIDORES NTP
# En el parámetro "ntp_servers" introducir todas las ip's necesarias
ntp_servers:
    - 192.168.2.1
    - 192.168.2.2
    - 192.168.2.3

# DATOS DE SERVIDORES DNS
# En el parámetro "dns_servers" introducir todas las ip's necesarias
dns_servers:
    - 192.168.3.1
    - 192.168.3.2
