---
# PARAMETROS DE USUARIOS Y PASSWORDS
# En el parámetro "username" introducir el nombre del usuario
# En el parámetro "password" introducir el password del usuario
users:
  - username: user1
    password: password-user1

  - username: user2
    password: password-user2

