############################################################################
#                 ROL DE BACKUPS DE COMANDOS ESPECIFICOS                   # 
#                  PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                    # 
############################################################################

# # # EJECUTANDO EL COMANDO SOLICITADO # # #
- name: Ejecutando los comandos solicitados
  ios_command:
    commands:
      - "{{ comando_backup }}"           
  register: output

# # # GRABANDO EL COMANDO SOLICITADO EN SU RUTA CONCRETA DE LA CARPETA REPOSITORIO # # #
- name: Grabar la configuracion de los equipos de red
  copy:        
    content: "{{ output.stdout[0] }}"
    dest: ./playbooks/repositorio/{{ nombre_empresa }}/{{ backup_nombre_carpeta }}/{{ backup_nombre_archivo }}-{{ inventory_hostname }}.txt