---
#######################
# PARAMETROS GLOBALES #
#######################

######### 
# VLANS #
#########

vlans_parametros:

  - vlan_id: 10
    vlan_name: Redes
  - vlan_id: 20
    vlan_name: Ventas
  - vlan_id: 30
    vlan_name: Administrativos

#######################
# MODO TRUNK Y ACCESS #
#######################

# # # MODO TRUNK # # #
trunk_parametros:

  - trunk_puerto: g0/3
  - trunk_puerto: g0/1
  - trunk_puerto: g1/1