---
#######################
# PARAMETROS GLOBALES #
#######################

# # # OJO - SE NECESITA CREAR UN ARCHIVO CON EL NOMBRE DE CADA HOST (EQUIPO DE RED) # # #
# # # OJO - ESTOS ARCHIVOS TIENEN QUE SER CON EXTENSION YAML ".yml"                 # # #
# # # OJO - SIGA LAS INSTRUCCIONES DE LOS PARAMETROS QUE REQUIERA SU RED            # # #

################
# ETHERCHANNEL #
################

etherchannel_capa2_parametros:

  - etherchannel_numero: 1 
    etherchannel_range: g1/0,g2/0
  - etherchannel_numero: 3 
    etherchannel_range: g1/1,g1/2

######### 
# VLANS #
#########

vlans_parametros:

  - vlan_id: 10
    vlan_name: Redes
  - vlan_id: 20
    vlan_name: Ventas
  - vlan_id: 30
    vlan_name: Administrativos

#######################
# MODO TRUNK Y ACCESS #
#######################

# # # MODO TRUNK # # #
trunk_parametros:

  - trunk_puerto: port-channel 1
  - trunk_puerto: port-channel 3

# # # MODO ACCESS # # #
access_parametros:

  - access_puerto: g3/1
    access_vlan: 10
  - access_puerto: g3/2
    access_vlan: 20
  - access_puerto: g3/3
    access_vlan: 30