---
- name: RESETEAR PARAMETROS DE ROUTER/SWITCH
  hosts: all
  gather_facts: no

  tasks:
     
    - name: RESETEAR PUERTOS
      ios_config:
        lines:
          - interface {{ item.puerto_id }}          
          - no ip address 
          - shutdown      
      loop: "{{ puertos_parametros }}"

    - name: RESETEAR OSPF
      ios_config:
        lines:                    
          - no router ospf 1  

    - name: RESETEAR USUARIOS 
      ios_user:
        aggregate:
        - name: esteban
        purge: yes




      #   lines:          
      #     - no username "{{ item.username }}" 
      # loop: "{{ users }}"