---
############################################################################
#         CONSULTA DE INTERFACES A TODOS LOS EQUIPOS DEL INVENTORY         # 
#                    PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                  #
############################################################################

- name: Ejecutando el comando "show ip interface brief"
  hosts: all
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL VISUALIZAR # # #
    - include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show ip interface brief"