---
############################################################################
#            CONSULTA DE OSPF A TODOS LOS EQUIPOS DEL INVENTORY            #
#                    PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                  #
############################################################################

- name: Comandos Show para OSPF
  hosts: 
    equipos-ospf-router
    equipos-ospf-switch
  gather_facts: no
  tasks:
    - name: Ejecutando el comando "show ip ospf neighbor"
      # # # LLAMADO A ROL VISUALIZAR # # #
      include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show ip ospf neighbor"
    - name: Ejecutando el comando "show running-config | section ospf"
      # # # LLAMADO A ROL VISUALIZAR # # #
      include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show running-config | section ospf"
