---
############################################################################
# VERIFICACION DE CONEXION POR MEDIO DEL MODULO PING A TODOS LOS EQUIPOS   #
# DEL INVENTORY         PRECAUCIÓN!!! NO MODIFICAR EL CODIGO               #
############################################################################

- name: Verificar conexión total a todos los equipos
  hosts: all
  gather_facts: no
  connection: local
  tasks:  
    # # # PING A TODA LA RED DE LA EMPRESA # # #
    - name: TEST DE ACCESIBILIDAD A LA RED
      ios_ping:
        dest: "{{ item.ips_id }}" 
      loop: "{{ ips }}"   
   