---
# PARAMETROS GLOBALES
loopback: 2.2.2.2
router_id: 2.2.2.2

# OSPF
ospf_parametros:
  - ospf_network: 172.16.0.200 
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.208
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.212
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.216
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.232
    ospf_wildcard: 0.0.0.3
    ospf_area: 0

# PUERTOS
puertos_parametros:
  - puerto_id: g0/1
    puerto_ip: 172.16.0.202
    puerto_mascara: 255.255.255.252
  - puerto_id: g1/0
    puerto_ip: 172.16.0.209
    puerto_mascara: 255.255.255.252
  - puerto_id: g1/1
    puerto_ip: 172.16.0.213
    puerto_mascara: 255.255.255.252
  - puerto_id: g1/2
    puerto_ip: 172.16.0.217
    puerto_mascara: 255.255.255.252

# ETHERCHANNEL

etherchannel_numero: 1
etherchannel_ip: 172.16.0.233  
etherchannel_mascara: 255.255.255.252
etherchannel_range: g1/3,g2/3
