---
# PARAMETROS GLOBALES
loopback: 3.3.3.3
router_id: 3.3.3.3

# OSPF
ospf_parametros:
  - ospf_network: 172.16.0.204 
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.220
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.224
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.228
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 172.16.0.232
    ospf_wildcard: 0.0.0.3
    ospf_area: 0

# PUERTOS
puertos_parametros:
  - puerto_id: g0/2
    puerto_ip: 172.16.0.206
    puerto_mascara: 255.255.255.252
  # - puerto_id: g2/0
  #   puerto_ip: 172.16.0.221
  #   puerto_mascara: 255.255.255.252
  # - puerto_id: g2/1
  #   puerto_ip: 172.16.0.225
  #   puerto_mascara: 255.255.255.252
  # - puerto_id: g2/2
  #   puerto_ip: 172.16.0.229
  #   puerto_mascara: 255.255.255.252

# ETHERCHANNEL

etherchannel_capa3_parametros:
  - etherchannel_numero: 1
    etherchannel_ip: 172.16.0.234  
    etherchannel_mascara: 255.255.255.252
    etherchannel_range: g1/3,g2/3

etherchannel_capa2_parametros:
  - etherchannel_numero: 5 
    etherchannel_range: g2/0,g3/0
  - etherchannel_numero: 6 
    etherchannel_range: g2/1,g3/1
  - etherchannel_numero: 7 
    etherchannel_range: g2/2,g3/2