---
#######################
# PARAMETROS GLOBALES #
#######################

############################
# CONFIGURACION DE PUERTOS #
############################

puertos_parametros:
  - puerto_id: g0/1
    puerto_ip: 10.10.10.2
    puerto_mascara: 255.255.255.252

################
# ETHERCHANNEL #
################

etherchannel_capa3_parametros:
  - etherchannel_numero: 1
    etherchannel_ip: 192.168.30.1
    etherchannel_mascara: 255.255.255.252
    etherchannel_range: g3/2,g3/3 

########
# OSPF #
########

loopback: 2.2.2.2
router_id: 2.2.2.2
ospf_parametros: 
  - ospf_network: 10.10.10.0
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 10.10.30.0
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 192.168.10.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.20.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.30.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.40.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.50.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.60.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0


######### 
# VLANS #
#########

vlans_parametros:
  - vlan_id: 10
    vlan_name: Redes
  - vlan_id: 20
    vlan_name: Financiero
  - vlan_id: 30
    vlan_name: Marketing
  - vlan_id: 40
    vlan_name: Comercial
  - vlan_id: 50
    vlan_name: Gestion
  - vlan_id: 60
    vlan_name: Operaciones

#######################
# MODO TRUNK Y ACCESS #
#######################

# # # MODO TRUNK # # #
trunk_parametros:
  - trunk_puerto: g1/0
  - trunk_puerto: g1/1
  - trunk_puerto: g1/2

########
# HSRP #
########

# # # HSRP SWITCH "ACTIVO" # # #
hsrp_switch_activo: 
  - hsrp_vlan: 10
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.10.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.10.1 
    hsrp_prioridad: 200
  - hsrp_vlan: 20
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.20.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.20.1 
    hsrp_prioridad: 200
  - hsrp_vlan: 30
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.30.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.30.1 
    hsrp_prioridad: 200
  - hsrp_vlan: 40
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.40.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.40.1 
    hsrp_prioridad: 200
  - hsrp_vlan: 50
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.50.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.50.1 
    hsrp_prioridad: 200
  - hsrp_vlan: 60
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.60.2
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.60.1 
    hsrp_prioridad: 200
