---
############################################################################
#                            PARAMETROS GLOBALES                           #
#               ATENCION!!! LEA ATENTAMENTE LAS INSTRUCCIONES              #
############################################################################

############################################################################
#                         CONFIGURACION DE PUERTOS                         #
############################################################################

puertos_parametros:
  - puerto_id: g0/2
    puerto_ip: 10.10.20.2
    puerto_mascara: 255.255.255.252

############################################################################
#                                ETHERCHANNEL                              #
############################################################################

etherchannel_capa3_parametros:
  - etherchannel_numero: 1
    etherchannel_ip: 10.10.30.2
    etherchannel_mascara: 255.255.255.252
    etherchannel_range: g3/2,g3/3

############################################################################
#                                  OSPF                                    #
############################################################################

loopback: 3.3.3.3
router_id: 3.3.3.3
ospf_parametros:
  - ospf_network: 10.10.20.0
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 10.10.30.0
    ospf_wildcard: 0.0.0.3
    ospf_area: 0
  - ospf_network: 192.168.10.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.20.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.30.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.40.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.50.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0
  - ospf_network: 192.168.60.0
    ospf_wildcard: 0.0.0.255
    ospf_area: 0

############################################################################ 
#                                VLANS                                     #
############################################################################

vlans_parametros:
  - vlan_id: 10
    vlan_name: Redes
  - vlan_id: 20
    vlan_name: Financiero
  - vlan_id: 30
    vlan_name: Marketing
  - vlan_id: 40
    vlan_name: Comercial
  - vlan_id: 50
    vlan_name: Gestion
  - vlan_id: 60
    vlan_name: Operaciones

############################################################################
#                         MODO TRUNK Y ACCESS                              #
############################################################################

# # # MODO TRUNK # # #
trunk_parametros:
  - trunk_puerto: g2/0
  - trunk_puerto: g2/1
  - trunk_puerto: g2/2

############################################################################
#                                   HSRP                                   #
############################################################################

# # # HSRP SWITCH "STANDBY" # # #
hsrp_switch_standby:
  - hsrp_vlan: 10
    hsrp_numero: 1
    hsrp_ip_equipo: 192.168.10.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.10.1 
  - hsrp_vlan: 20
    hsrp_numero: 2
    hsrp_ip_equipo: 192.168.20.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.20.1 
  - hsrp_vlan: 30
    hsrp_numero: 3
    hsrp_ip_equipo: 192.168.30.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.30.1 
  - hsrp_vlan: 40
    hsrp_numero: 4
    hsrp_ip_equipo: 192.168.40.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.40.1 
  - hsrp_vlan: 50
    hsrp_numero: 5
    hsrp_ip_equipo: 192.168.50.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.50.1 
  - hsrp_vlan: 60
    hsrp_numero: 6
    hsrp_ip_equipo: 192.168.60.3
    hsrp_mascara: 255.255.255.0
    hsrp_ip_gateway: 192.168.60.1 