---
# PARAMETROS GLOBALES
loopback: 3.3.3.3
router_id: 3.3.3.3

# PUERTOS
puertos_parametros:
  - puerto_id: g0/2
    puerto_ip: 172.16.0.206
    puerto_mascara: 255.255.255.252
  - puerto_id: g1/3
    puerto_ip: 172.16.0.194
    puerto_mascara: 255.255.255.248
  - puerto_id: g2/3
    puerto_ip: 172.16.0.196
    puerto_mascara: 255.255.255.248
  - puerto_id: g2/0
    puerto_ip: 172.16.0.221
    puerto_mascara: 255.255.255.252
  - puerto_id: g2/1
    puerto_ip: 172.16.0.225
    puerto_mascara: 255.255.255.252
  - puerto_id: g2/2
    puerto_ip: 172.16.0.229
    puerto_mascara: 255.255.255.252