# CREACIÓN DEL REPOSITORIO #

- stat:
    path: ./playbooks/repositorio/{{ nombre_empresa }}/{{ repositorio_nombre_carpeta }}
  register: output
- name: Crear directorio 
  file: 
    path: ./playbooks/repositorio/{{ nombre_empresa }}/{{ repositorio_nombre_carpeta }}/       
    state: directory
  when: output.stat.exists == false