############################################################################
#  ROL DE CONFIGURACION DE PUERTOS EN EQUIPOS DE ACUERDO A PARAMETROS EN   # 
#  INVENTORY              !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO          # 
############################################################################

# # # CONFIGURACION DE PUERTOS # # #
- name: Configurar PUERTOS
  ios_config:
    lines:
      - interface {{ item.puerto_id }}          
      - ip address {{ item.puerto_ip }} {{ item.puerto_mascara }} 
      - no shutdown      
  loop: "{{ puertos_parametros }}"