---
- name: Configuración del login del banner
  hosts: router1
  gather_facts: no

  tasks:
    - name: Remover antiguo banner
      ios_banner:
        banner: motd
        state: absent

    - name: Configurando el banner desde un archivo
      ios_banner:
        banner: motd
        text: "{{ lookup('file', './parametros/banner.cfg') }}"
        state: present  

        