---
vlans:
  - vlan_name: VLAN10
    vlan_id: 10
  
  - vlan_name: VLAN20
    vlan_id: 20
  
  - vlan_name: VLAN30
    vlan_id: 30
  
  - vlan_name: VLAN40
    vlan_id: 40
  
  - vlan_name: VLAN50
    vlan_id: 50

  - vlan_name: VLAN60
    vlan_id: 60

    