---
##############################################################################
# CONFIGURACION DE PUERTOS DE UN ROUTER DE ACUERDO A PARAMETROS EN INVENTORY #
#             !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                        # 
##############################################################################

- name: Configurar PUERTOS ROUTER
  hosts: router
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL CONFIGURAR PUERTOS # # #
    - include_role:
        name: configurar-puertos
        
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #
    - include_role:
        name: guardar-configuracion