---
##############################################################################
# CONFIGURACION DE PUERTOS DE UN SWITCH DE ACUERDO A PARAMETROS EN INVENTORY #
##############################################################################


- name: Configurar PUERTOS SWITCH
  hosts: switch
  gather_facts: no
  tasks:

    # # # CONFIGURANDO LOS PUERTOS A "NO SWITCHPORT" # # # 
    - name: Configurar PUERTOS a NO SWITCHPORT
      ios_config:
        lines:
          - ip routing
          - interface {{ item.puerto_id }}          
          - no switchport                
      loop: "{{ puertos_parametros }}"

    # # # LLAMADO A ROL CONFIGURAR PUERTOS # # #
    - include_role:
        name: configurar-puertos   