---
############################################################################
#    CONFIGURACION DE ETHERCHANNEL EN EQUIPOS DE ACUERDO A PARAMETROS EN   # 
#    INVENTORY          !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configuracion de etherchannel capa 2
  hosts: equipos-etherchannel-capa2 
  gather_facts: no
  tasks:   
    # # # CREANDO EL PORT-CHANNEL EN EL EQUIPO # # #  
    - name: Preparando etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}" 
    # # # CONFIGURANDO LAS INTERFACES PARA EL PORT-CHANNEL EN EL EQUIPO #  # 
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no shutdown
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_capa2_parametros }}"

    # # # ACTIVANDO EL PORT-CHANNEL EN EL EQUIPO # # #
    - name: Confirmando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}"
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #
    - include_role:
        name: guardar-configuracion
- name: Configuracion de etherchannel capa 3
  hosts: equipos-etherchannel-capa3
  gather_facts: no
  tasks:
    # # # CREANDO EL PORT-CHANNEL EN EL EQUIPO # # #  
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}
          - no switchport   
          - ip address {{ item.etherchannel_ip }} {{ item.etherchannel_mascara }}  
      loop: "{{ etherchannel_capa3_parametros }}"        
    # # # CONFIGURANDO LAS INTERFACES PARA EL PORT-CHANNEL EN EL EQUIPO #  #
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no switchport 
          - no ip address
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_capa3_parametros }}" 
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #
    - include_role:
        name: guardar-configuracion
