---
############################################################################
#        CONFIGURACION DE OSPF EN EQUIPOS DE ACUERDO A PARAMETROS EN       # 
#        INVENTORY      !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configuracion IP ROUTING
  hosts: equipos-ospf-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL IP ROUTING EN EL SWITCH # # # 
    - ios_config:
        lines:
          - ip routing             
      loop: "{{ ospf_parametros }}"

- name: Configuracion OSPF
  hosts: equipos-ospf-router, equipos-ospf-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL LOOPBACK EN EL EQUIPO # # # 
    - name: Configuracion loopback
      ios_config:
        lines:
          - ip address {{ loopback }} 255.255.255.255
        parents: interface loopback 1
    # # # CONFIGURANDO EL ROUTER-ID EN EL EQUIPO # # #   
    - name: Configuracion ROUTER ID
      ios_config:
        lines:
          - router-id {{ router_id }}    
        parents: router ospf 1      
    # # # DECLARANDO LAS NETWORK DEL OSPF EN EL EQUIPO # # # 
    - name: Declaracion "network" OSPF
      ios_config:
        lines:           
          - network {{ item.ospf_network }} {{ item.ospf_wildcard }} area {{ item.ospf_area }}
        parents: router ospf 1
      loop: "{{ ospf_parametros }}"



        

