---
- name: Configurar ETHERCHANNEL
  hosts: equipos-etherchannel-capa2 
  gather_facts: no
  tasks:     
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}" 
     
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no shutdown
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_capa2_parametros }}"

    - name: Confirmando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}" 

