---
- name: Configurar IP ROUTING
  hosts: equipos-ospf-switch
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - ip routing             
      loop: "{{ ospf_parametros }}"
- name: Configurar OSPF
  hosts: equipos-ospf-router, equipos-ospf-switch
  gather_facts: no

  tasks:
    - name: Configurar loopback
      ios_config:
        lines:
          - ip address {{ loopback }} 255.255.255.255
        parents: interface loopback 1
      
    - name: Configurar ROUTER ID
      ios_config:
        lines:
          - router-id {{ router_id }}    
        parents: router ospf 1      
  
    - name: Configurar OSPF
      ios_config:
        lines:           
          - network {{ item.ospf_network }} {{ item.ospf_wildcard }} area {{ item.ospf_area }}
        parents: router ospf 1
      loop: "{{ ospf_parametros }}"



        

