---
############################################################################
#       CONFIGURACION DE VLANS EN EQUIPOS DE ACUERDO A PARAMETROS EN       # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Crear Vlans en cada equipo
  hosts: equipos-vlan
  gather_facts: no
  tasks:
    # # # CREANDO LAS VLANS EN LOS EQUIPOS # # # 
    - ios_config:
        lines:
          - name {{ item.vlan_name }}
          - no shutdown
        parents: vlan {{ item.vlan_id }}
      loop: "{{ vlans_parametros }}"

- name: Modo Troncal
  hosts: equipos-vlan-trunk
  gather_facts: no
  serial: 1
  tasks:
    # # # ASIGNANDO EL MODO TRONCAL EN LAS INTERFACES DE LOS EQUIPOS # # # 
    - ios_config:
        lines:
          - interface {{ item.trunk_puerto }}
          - switchport trunk encapsulation dot1q 
          - switchport mode trunk
          - switchport nonegotiate
          - no shutdown
      loop: "{{ trunk_parametros }}"

- name: Modo Acceso
  hosts: equipos-vlan-access
  gather_facts: no
  tasks:
    # # # ASIGNANDO EL MODO ACCESS EN LAS INTERFACES DE LOS EQUIPOS # # #
    - ios_config:
        lines:
          - interface {{ item.access_puerto }} 
          - switchport mode access 
          - switchport access vlan {{ item.access_vlan }}
          - no shutdown
      loop: "{{ access_parametros }}"

- name: INTER-VLANS ROUTER
  hosts: equipo-inter-vlans-router
  gather_facts: no
  tasks:
    # # # ENCENDIDO DEL SUB-PUERTO DEL ROUTER # # #
    - name: Encendiendo el puerto INTER-VLANS en ROUTER
      ios_config:
        lines:
          - interface {{ item.inter_vlan_puerto }}
          - no shutdown 
      loop: "{{ inter_vlans_router_parametros }}"
    # # # CONFIGURANDO EL INTER-VLAN EN EL SUB-PUERTO DEL ROUTER # # #
    - name: Configurando INTER-VLANS en ROUTER
      ios_config:
        lines:
          - interface {{ item.inter_vlan_puerto }}.{{ item.inter_vlan_numero }}  
          - encapsulation dot1q {{ item.inter_vlan_numero }}
          - ip address {{ item.inter_vlan_ip }} {{ item.inter_vlan_mascara }} 
          - no shutdown  
      loop: "{{ inter_vlans_router_parametros }}"

- name: INTER-VLANS SWITCH
  hosts: equipo-inter-vlans-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL MODO TRUNK EN LA SVI DEL SWITCH # # #
    - name: Configuracion el puerto del switch
      ios_config:
        lines:
          - ip routing
          - interface {{ item.inter_vlan_puerto }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown  
      loop: "{{ inter_vlans_switch_parametros }}"
    # # # CONFIGURANDO LA IP EN LA SVI DEL SWITCH # # #
    - name: Configuracion la ip de la INTER-VLAN 
      ios_config:
        lines:
          - interface vlan {{ item.inter_vlan_numero }}  
          - ip address {{ item.inter_vlan_ip }} {{ item.inter_vlan_mascara }}
          - no shutdown
      loop: "{{ inter_vlans_switch_parametros }}"

- name: Guardando la CONFIGURACION
  hosts: equipos-vlan
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #
    - include_role:
        name: guardar-configuracion




    






