---
############################################################################
#       CONFIGURACION DE HSRP EN EQUIPOS DE ACUERDO A PARAMETROS EN        # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configurando SWITCH HSRP ACTIVO
  hosts: equipo-hsrp-activo-switch
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP ACTIVO EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero }} ip {{ item.hsrp_ip_gateway }}
          - standby {{ item.hsrp_numero }} priority {{ item.hsrp_prioridad }}
          - standby {{ item.hsrp_numero }} preempt 
          - no shutdown
      loop: "{{ hsrp_switch_activo }}"

- name: Configurando SWITCH HSRP STANDBY
  hosts: equipos-hsrp-standby-switch
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP STANDBY EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero }} ip {{ item.hsrp_ip_gateway }} 
          - no shutdown     
      loop: "{{ hsrp_switch_standby }}"
    
- name: Ejecutando el comando "show standby"
  hosts: equipo-hsrp-activo-switch, equipos-hsrp-standby-switch
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL VISUALIZAR # # #
    - include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show standby"
        
- name: Configurando ROUTER HSRP ACTIVO
  hosts: equipo-hsrp-activo-router
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP ACTIVO EN EL ROUTER # # # 
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - encapsulation dot1q {{ item.hsrp_numero_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero}} ip {{ item.hsrp_ip_gateway }}
          - standby {{ item.hsrp_numero}} priority {{ item.hsrp_prioridad }}
          - standby {{ item.hsrp_numero}} preempt        
      loop: "{{ hsrp_router_activo }}"

- name: Configurando ROUTER HSRP STANDBY
  hosts: equipos-hsrp-standby-router
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP STANDBY EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - encapsulation dot1q {{ item.hsrp_numero_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero}} ip {{ item.hsrp_ip_gateway }}      
      loop: "{{ hsrp_router_standby }}"
    
- name: Ejecutando el comando "show standby"
  hosts: equipo-hsrp-activo-router, equipos-hsrp-standby-router
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL VISUALIZAR # # #
    - include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show standby"