---
############################################################################
#    CONFIGURACION DE ACCESS-LIST EN EQUIPOS DE ACUERDO A PARAMETROS EN    # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################
- hosts: ios
  gather_facts: no
  tasks:
    - name: configure ip access list
      ios_config:
        lines:
          - 10 permit ip host 192.0.2.1 any log
          - 20 permit ip host 192.0.2.2 any log
          - 30 permit ip host 192.0.2.3 any log
          - 40 permit ip host 192.0.2.4 any log
          - 50 permit ip host 192.0.2.5 any log
        parents: ip access-list extended ansible-demo
        before: no ip access-list extended ansible-demo
    - name: configurable backup path
      ios_config:
        src: ios_template.j2
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: ./
          
- hosts: network
  gather_facts: false
  connection: local

  vars:
    cli:
      username: nms
      password: cisco
  
  tasks:

    - name: create access list VTY_ACCESS
      ios_config:
        provider: "{{cli}}"
        lines:
          permit host 192.168.0.100
        parents:
          ip access-list standard VTY_ACCESS
        save_when: changed

    - name: apply access list to VTY lines
      ios_config:
        provider: "{{cli}}"
        lines:
          access-class VTY_ACCESS in
        parents:
          line vty 0 4
        save_when: changed
    
    - name: pull device configurations
      ios_command:
        provider: "{{cli}}"
        commands:
          show run | begin VTY_ACCESS
      
      register: show_run_output

    - name: print output to screen
      debug:
        var=show_run_output.stdout_lines