---
- name: Crear Vlans
  hosts: equipos-vlan
  gather_facts: no

  tasks:
    # - name: Crear Vlans en cada equipo
    #   ios_config:
    #     lines:
    #       - name "{{ item.vlan_name }}"
    #       - no shutdown
    #     parents: "vlan {{ item.vlan_id }}"
    #   loop: "{{ vlans }}"
    
    - name: Add interfaces to VLAN
      ios_vlan:
        vlan_id: "{{ item.vlan_id }}"
        interfaces:
        - "{{ item.vlan_interface }}"
      loop: "{{ vlans_parametros }}"

- name: Configurando INTER-VLANS
  hosts: equipos-inter-vlan
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.inter_vlan_id }}.{{ item.inter_vlan_numero }}  
          - encapsulation dot1q {{ item.inter_vlan_numero }}
          - ip address {{ item.inter_vlan_ip }} {{ item.inter_vlan_mascara }}   
      loop: "{{ inter_vlan_parametros }}" 