---
- name: Configurar ETHERCHANNEL
  hosts: equipos-etherchannel-capa2
 # hosts: switch-core1, switch-core2
  gather_facts: no

  tasks:
     
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk  
         # - switchport trunk native vlan {{ vlan_nativa }}   
      loop: "{{ etherchannel_capa2_parametros }}" 
     
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - shutdown
          - channel-group {{ item.etherchannel_numero }} mode active
        #  - switchport trunk native vlan {{ vlan_nativa }}
          - no shutdown
      loop: "{{ etherchannel_capa2_parametros }}"

