---
############################################################################
#     BACKUP GENERAL DE EQUIPOS EN GIT-LAB Y EN CARPETA REPOSITORIOS       # 
#                !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                   # 
############################################################################
- name: Backup Local
  hosts: all 
  gather_facts: no
  tasks:

    # # # CREACIÓN DEL REPOSITORIO # # #

    # CREACIÓN DEL DIRECTORIO "backup-show-arp" # 
    - include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_arp
  
    # CREACIÓN DEL DIRECTORIO "backup-show-ip_int_br" #
    - include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_ip_int_br

    # CREACIÓN DEL DIRECTORIO "backup-show-run" #
    - include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_run

    # CREACIÓN DEL DIRECTORIO "detalle-de-equipos" # 
    - include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: detalle-de-equipos

    # # # GENERACIÓN DE BACKUPS EN DIRECTORIOS # # #

    # BACKUP "show arp" #
    - include_role:
        name: backups 
      vars:
        comando_backup: "show arp" 
        backup_nombre_archivo: "arp" 
        backup_nombre_carpeta: backup-show_arp           

    # BACKUP "show ip interface brief" #
    - include_role:
        name: backups 
      vars:
        comando_backup: "show ip interface brief" 
        backup_nombre_archivo: "ip-int-br" 
        backup_nombre_carpeta: backup-show_ip_int_br     
  
    # BACKUP "show run" #
    - include_role:
        name: backups 
      vars:
        comando_backup: "show run" 
        backup_nombre_archivo: "run" 
        backup_nombre_carpeta: backup-show_run  

    # BACKUP "detalle de equipos" #
    - name: Obteniendo los parametros de los equipos de red
      ios_facts:
        gather_subset: all  
    - name: Grabando los parametros de los equipos de red
      template:
        src: ./template/detalle-de-equipos.j2
        dest: ./playbooks/repositorio/{{ nombre_empresa }}/detalle-de-equipos/detalle-de-equipos.csv

# # # BACKUPS A GITLAB # # #

# BACKUP SHOW ARP #
- name: Backup GITLAB "show arp"
  hosts: all 
  gather_facts: no
  tasks:  
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "arp-"
        git_ruta: "backup-show_arp"
        mensaje_commit: "backup tablas arp"
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".txt"
- name: Push GITLAB "show arp"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab

# BACKUP SHOW IP INTERFACE BRIEF #
- name: Backup GITLAB "show ip interface brief"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "ip-int-br-"
        git_ruta: "backup-show_ip_int_br"
        mensaje_commit: "backup show ip interface brief" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".txt"
- name: Push GITLAB "show ip interface brief"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab

# BACKUP SHOW RUN #
- name: Backup GITLAB "show run"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "run-"
        git_ruta: "backup-show_run"
        mensaje_commit: "backup show run" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".txt"
- name: Push GITLAB "show run"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab







# # BACKUP DETALLE DE EQUIPOS #
# - name: Backup GITLAB "detalle de equipos"
#   hosts: localhost 
#   gather_facts: no
#   tasks:  
#     - include_role:
#         name: gitlab
#       vars: 
#         git_prefijo: "detalle-de-equipos"
#         git_ruta: "detalle-de-equipos"
#         mensaje_commit: "backup detalle de equipos"
#         nombre_equipo: ""
#         extension: ".csv"


#     - name: Creando action list
#       set_fact:
#         action_list: "{{ action_list | default([]) + [ hostvars[item].action_dict ] }}"
#       loop: "{{ groups['all'] }}"
#       when: hostvars[item].action_dict != {}

#     - name: Creando action list
#       set_fact:
#         # dir_path: ./repositorio/{{ nombre_empresa }}/detalle-de-equipos/
#         # with_file: "./repositorio/{{ nombre_empresa }}/detalle-de-equipos/detalle-de-equipos.csv"
#         archivo: "./playbooks/repositorio/{{ nombre_empresa}}/detalle-de-equipos/detalle-de-equipos.csv"
#         action_list: "{{ action_list | default([]) + [ archivo.action_dict ] }}"
#       #loop: "{{ groups['all'] }}"
#       when: archivo.action_dict != {}

#     - name: Push nuevo/actualizado a gitlab
#       uri:
#         url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/commits
#         headers:
#           Private-Token: "{{ gitlab_access_token }}"
#         validate_certs: no
#         method: POST
#         body:
#           branch: master
#           commit_message: backup general 
#           actions: "{{ action_list }}"
#         status_code: 201
#         body_format: json
#       delegate_to: localhost
#      when: action_list is defined
  