---
############################################################################
#                           BACKUP A GIT- LAB                              # 
#                   PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                   # 
############################################################################

# BACKUP DE EQUIPOS."CFG" #
- name: Back-up de equipos "cfg"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: ""
        git_ruta: "07-show_run-cfg"
        mensaje_commit: "backup equipos .CFG" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".cfg"
- name: Push Git-Lab ".cfg"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab
# BACKUP DE DETALLE DE EQUIPOS #
- name: Push Git-Lab "detalle-de-equipos.csv"
  hosts: localhost
  gather_facts: no
  tasks:
    # # # LECTURA DEL CONTENIDO DE LOS ARCHIVOS EN EL INVENTORY # # #
    - name: Lectura del contenido de los archivos txt
      set_fact:
        dir_path: ./repositorio/{{ nombre_empresa }}/detalle-de-equipos/    
        file_content: "{{ item }}"      
      with_file:
        - "./repositorio/{{ nombre_empresa }}/detalle-de-equipos/detalle-de-equipos.csv"      
      no_log: True
    # # # GENERANDO EL ARBOL DE ARCHIVOS DEL REPOSITORIO # # #
    - name: Obtener el árbol de archivos del repositorio
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/tree?ref=master&per_page=100&page=1
        body_format: json
        validate_certs: no  
        status_code: 200
        return_content: yes
        headers:
          Private-Token: "{{ gitlab_access_token }}"
      register: response
      delegate_to: localhost
    # # # OBTENIENDO LOS ARCHIVOS DEL REPOSITORIO # # #
    - name: Obtener los archivos del proyecto
      set_fact:
        project_files: "{{ response.json | json_query('[].name') }}"
        file_name: "detalle-de-equipos.csv"
    # # # ESTABLECIENDO ACCION "CREATE" CUANDO NO EXISTAN ARCHIVOS EN EL PROYECTO # # #
    - name: Establecer la acción de confirmación como "create"
      set_fact:
        commit_action: create
      when: file_name is not in project_files
    # # # ESTABLECIENDO ACCION "UPDATE" CUANDO EXISTAN ARCHIVOS EN EL PROYECTO # # #
    - name: Establecer la acción de confirmación como "update"
      set_fact:
        commit_action: update
      when: file_name in project_files
    # # # OBTENIENDO EL CONTENIDO DE LOS ARCHIVOS EN GITLAB CUANDO LA ACCION SEA "UPDATE" # # #
    - name: Obtener el contenido del archivo de gitlab
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/files/{{ file_name }}/raw?ref=master
        body_format: json
        validate_certs: no
        status_code: 200, 404
        return_content: yes
        headers:
          Private-Token: "{{ gitlab_access_token }}"
      register: response
      delegate_to: localhost
      when: commit_action == "update"
    # # # GRABANDO EL CONTENIDO DE LOS ARCHIVOS EN GITLAB CUANDO LA ACCION SEA "UPDATE" # # #
    - name: Grabando el contenido del archivo de gitlab
      set_fact:
        file_content_in_gitlab: "{{ response.content }}"
      when: commit_action == "update"
    # # # CREANDO EL ACTION DICT CUANDO ESTE "CREATE" O EN "UPDATE" NO HAYA CONTENIDO # # #
    - name: Creando el action dict
      set_fact:
        action_dict:
          action: "{{ commit_action}}"
          file_path: "detalle-de-equipos.csv"
          content: "{{ file_content }}.csv" 
      when: commit_action == "create" or (commit_action == "update" and file_content_in_gitlab != file_content)
    # # # CREANDO EL DICT VACIO CUANDO LA ACCION SEA "UPDATE" Y EXISTA CONTENIDO # # #
    - name: Creando empty dict
      set_fact:
        action_dict: {}
      when: commit_action == "update" and file_content_in_gitlab == file_content
    # # # PUSH A GITLAB CUANDO EL ACTION LIST ESTE DEFINIDO # # #
    - name: Push nuevo/actualizado a gitlab
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/commits
        headers:
          Private-Token: "{{ gitlab_access_token }}"
        validate_certs: no
        method: POST
        body:
          branch: master
          commit_message: backup detalle-de-equipos.csv 
          actions: 
            - action: "{{ commit_action }}"
              file_path: "detalle-de-equipos.csv"
              content: "{{ file_content }}.csv"            
        status_code: 201
        body_format: json
      delegate_to: localhost