---
- name: DATOS GENERALES
  hosts: all
  gather_facts: no

  tasks:

    - name: Ejecutando el comando "show ip ospf neighbor"
      include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show ip ospf neighbor"

    - name: Ejecutando el comando "show running-config | section ospf"
      include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show running-config | section ospf"

- name: DATOS GENERALES
  hosts: equipos-etherchannel
  gather_facts: no

  tasks:
    - include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show etherchannel summary"
