---
- name: RESETEAR PUERTOS ROUTER
  hosts: router
  gather_facts: no
  tasks:
    - ios_config:
        lines:
          - interface {{ item.puerto_id }}          
          - no ip address 
          - shutdown      
      loop: "{{ puertos_parametros }}"

- name: RESETEAR PUERTOS SWITCH
  hosts: switch
  gather_facts: no
  tasks:     
    - ios_config:
        lines:
          - interface {{ item.puerto_id }}          
          - no ip address
          - switchport 
          - shutdown      
      loop: "{{ puertos_parametros }}"

- name: RESETEAR PARAMETROS DE ROUTER/SWITCH
  hosts: all
  gather_facts: no
  tasks:    
    - name: RESETEAR OSPF
      ios_config:
        lines:                    
          - no router ospf 1  
    - name: RESETEAR USUARIOS 
      ios_user:
        aggregate:
        - name: esteban
        purge: yes
    - name: REMOVER BANNER
      ios_banner:
        banner: motd
        state: absent

- name: RESETEAR ETHERCHANNEL
  hosts: equipos-etherchannel
  gather_facts: no
  tasks:  
    - ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no channel-group {{ item.etherchannel_numero }} mode active
          - switchport
          - shutdown
      loop: "{{ etherchannel_parametros }}"
    - ios_config:
        lines:
          - no interface port-channel {{ item.etherchannel_numero }}
      loop: "{{ etherchannel_parametros }}" 
