---
# BACKUP SHOW RUN #
- name: Backup GITLAB "show run"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "run-"
        git_ruta: "backup-show_run"
        mensaje_commit: "backup show run" 
- name: Push GITLAB "show run"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab