---
# BACKUP SHOW IP INTERFACE BRIEF #
- name: Backup GITLAB "show ip interface brief"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "ip-int-br-"
        git_ruta: "backup-show_ip_int_br"
        mensaje_commit: "backup show ip interface brief" 
- name: Push GITLAB "show ip interface brief"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab