---
# BACKUP SHOW ARP #
- name: Backup GITLAB "show arp"
  hosts: all 
  gather_facts: no
  tasks:  
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "arp-"
        git_ruta: "backup-show_arp"
        mensaje_commit: "backup tablas arp"
- name: Push GITLAB "show arp"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab