---
- hosts: all 
  gather_facts: no
  tasks:

    # # # # CREACIÓN DEL REPOSITORIO # # #

    # # CREACIÓN DEL DIRECTORIO "backup-show-arp" # 
    # - include_role:
    #     name: crear_repositorios
    #   vars: 
    #     repositorio_nombre_carpeta: backup-show_arp
  
    # # CREACIÓN DEL DIRECTORIO "backup-show-ip_int_br" #
    # - include_role:
    #     name: crear_repositorios
    #   vars: 
    #     repositorio_nombre_carpeta: backup-show_ip_int_br

    # # CREACIÓN DEL DIRECTORIO "backup-show-run" #
    # - include_role:
    #     name: crear_repositorios
    #   vars: 
    #     repositorio_nombre_carpeta: backup-show_run

    # # # # GENERACIÓNN DE BACKUPS EN DIRECTORIOS # # #

    # # BACKUP "show arp" #
    # - include_role:
    #     name: backups 
    #   vars:
    #     comando_backup: "show arp" 
    #     backup_nombre_archivo: "arp" 
    #     backup_nombre_carpeta: backup-show_arp           

    # # BACKUP "show ip interface brief" #
    # - include_role:
    #     name: backups 
    #   vars:
    #     comando_backup: "show ip interface brief" 
    #     backup_nombre_archivo: "ip-int-br" 
    #     backup_nombre_carpeta: backup-show_ip_int_br     
  
    # # BACKUP "show run" #
    # - include_role:
    #     name: backups 
    #   vars:
    #     comando_backup: "show run" 
    #     backup_nombre_archivo: "run" 
    #     backup_nombre_carpeta: backup-show_run     

    # # # A GITLAB # # #

    # GITLAB "show arp" #
    - include_role:
        name: gitlab
      vars: 
        backup_ruta: "backup-show_arp/arp"
        mensaje_commit: "backup tablas arp"
    
    # - include: algit.yml
    #   vars: 
    #     backup_ruta: "backup-show_arp/arp"
    #     mensaje_commit: "backup tablas arp"