---
############################################################################
#      CONFIGURACION DE PUERTOS EN EQUIPOS DE ACUERDO A PARAMETROS EN      # 
#      INVENTORY           !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO         # 
############################################################################

- name: Configuracion PUERTOS ROUTER
  hosts: router-puertos
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL CONFIGURAR PUERTOS # # #
    - include_role:
        name: configurar-puertos  
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #

- name: Configuracion PUERTOS SWITCH
  hosts: switch-puertos
  gather_facts: no
  tasks:
    # # # CONFIGURANDO LOS PUERTOS A "NO SWITCHPORT" # # # 
    - name: Configuracion PUERTOS a NO SWITCHPORT
      ios_config:
        lines:
          - ip routing
          - interface {{ item.puerto_id }}          
          - no switchport                
      loop: "{{ puertos_parametros }}"
    # # # LLAMADO A ROL CONFIGURAR PUERTOS # # #
    - include_role:
        name: configurar-puertos    

############################################################################
#    CONFIGURACION DE ETHERCHANNEL EN EQUIPOS DE ACUERDO A PARAMETROS EN   # 
#    INVENTORY          !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configuracion ETHERCHANNEL CAPA 2
  hosts: equipos-etherchannel-capa2 
  gather_facts: no
  tasks:   
    # # # CREANDO EL PORT-CHANNEL EN EL EQUIPO # # #  
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}" 
    # # # CONFIGURANDO LAS INTERFACES PARA EL PORT-CHANNEL EN EL EQUIPO #  # 
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no shutdown
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_capa2_parametros }}"

    # # # ACTIVANDO EL PORT-CHANNEL EN EL EQUIPO # # #
    - name: Confirmando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk    
      loop: "{{ etherchannel_capa2_parametros }}" 

- name: Configuracion ETHERCHANNEL CAPA 3
  hosts: equipos-etherchannel-capa3
  gather_facts: no
  tasks:
    # # # CREANDO EL PORT-CHANNEL EN EL EQUIPO # # #  
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}
          - no switchport   
          - ip address {{ item.etherchannel_ip }} {{ item.etherchannel_mascara }}  
      loop: "{{ etherchannel_capa3_parametros }}"        
    # # # CONFIGURANDO LAS INTERFACES PARA EL PORT-CHANNEL EN EL EQUIPO #  #
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - no switchport 
          - no ip address
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_capa3_parametros }}"

############################################################################
#        CONFIGURACION DE OSPF EN EQUIPOS DE ACUERDO A PARAMETROS EN       # 
#        INVENTORY      !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configuracion IP ROUTING
  hosts: equipos-ospf-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL IP ROUTING EN EL SWITCH # # # 
    - ios_config:
        lines:
          - ip routing             
      loop: "{{ ospf_parametros }}"

- name: Configuracion OSPF
  hosts: equipos-ospf-router, equipos-ospf-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL LOOPBACK EN EL EQUIPO # # # 
    - name: Configuracion loopback
      ios_config:
        lines:
          - ip address {{ loopback }} 255.255.255.255
        parents: interface loopback 1
    # # # CONFIGURANDO EL ROUTER-ID EN EL EQUIPO # # #   
    - name: Configuracion ROUTER ID
      ios_config:
        lines:
          - router-id {{ router_id }}    
        parents: router ospf 1      
    # # # DECLARANDO LAS NETWORK DEL OSPF EN EL EQUIPO # # # 
    - name: Declaracion "network" OSPF
      ios_config:
        lines:           
          - network {{ item.ospf_network }} {{ item.ospf_wildcard }} area {{ item.ospf_area }}
        parents: router ospf 1
      loop: "{{ ospf_parametros }}"

############################################################################
#       CONFIGURACION DE VLANS EN EQUIPOS DE ACUERDO A PARAMETROS EN       # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Crear Vlans en cada equipo
  hosts: equipos-vlan
  gather_facts: no
  tasks:
    # # # CREANDO LAS VLANS EN LOS EQUIPOS # # # 
    - ios_config:
        lines:
          - name {{ item.vlan_name }}
          - no shutdown
        parents: vlan {{ item.vlan_id }}
      loop: "{{ vlans_parametros }}"

- name: Modo Troncal
  hosts: equipos-vlan-trunk
  gather_facts: no
  serial: 1
  tasks:
    # # # ASIGNANDO EL MODO TRONCAL EN LAS INTERFACES DE LOS EQUIPOS # # # 
    - ios_config:
        lines:
          - interface {{ item.trunk_puerto }}
          - switchport trunk encapsulation dot1q 
          - switchport mode trunk
          - switchport nonegotiate
          - no shutdown
      loop: "{{ trunk_parametros }}"

- name: Modo Acceso
  hosts: equipos-vlan-access
  gather_facts: no
  tasks:
    # # # ASIGNANDO EL MODO ACCESS EN LAS INTERFACES DE LOS EQUIPOS # # #
    - ios_config:
        lines:
          - interface {{ item.access_puerto }} 
          - switchport mode access 
          - switchport access vlan {{ item.access_vlan }}
          - no shutdown
      loop: "{{ access_parametros }}"

- name: INTER-VLANS ROUTER
  hosts: equipo-inter-vlans-router
  gather_facts: no
  tasks:
    # # # ENCENDIDO DEL SUB-PUERTO DEL ROUTER # # #
    - name: Encendiendo el puerto INTER-VLANS en ROUTER
      ios_config:
        lines:
          - interface {{ item.inter_vlan_puerto }}
          - no shutdown 
      loop: "{{ inter_vlans_router_parametros }}"
    # # # CONFIGURANDO EL INTER-VLAN EN EL SUB-PUERTO DEL ROUTER # # #
    - name: Configurando INTER-VLANS en ROUTER
      ios_config:
        lines:
          - interface {{ item.inter_vlan_puerto }}.{{ item.inter_vlan_numero }}  
          - encapsulation dot1q {{ item.inter_vlan_numero }}
          - ip address {{ item.inter_vlan_ip }} {{ item.inter_vlan_mascara }} 
          - no shutdown  
      loop: "{{ inter_vlans_router_parametros }}"

- name: INTER-VLANS SWITCH
  hosts: equipo-inter-vlans-switch
  gather_facts: no
  tasks:
    # # # CONFIGURANDO EL MODO TRUNK EN LA SVI DEL SWITCH # # #
    - name: Configuracion el puerto del switch
      ios_config:
        lines:
          - ip routing
          - interface {{ item.inter_vlan_puerto }}  
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown  
      loop: "{{ inter_vlans_switch_parametros }}"
    # # # CONFIGURANDO LA IP EN LA SVI DEL SWITCH # # #
    - name: Configuracion la ip de la INTER-VLAN 
      ios_config:
        lines:
          - interface vlan {{ item.inter_vlan_numero }}  
          - ip address {{ item.inter_vlan_ip }} {{ item.inter_vlan_mascara }}
          - no shutdown
      loop: "{{ inter_vlans_switch_parametros }}"

############################################################################
#       CONFIGURACION DE HSRP EN EQUIPOS DE ACUERDO A PARAMETROS EN        # 
#       INVENTORY       !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configurando SWITCH HSRP ACTIVO
  hosts: equipo-hsrp-activo-switch
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP ACTIVO EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero }} ip {{ item.hsrp_ip_gateway }}
          - standby {{ item.hsrp_numero }} priority {{ item.hsrp_prioridad }}
          - standby {{ item.hsrp_numero }} preempt 
          - no shutdown
      loop: "{{ hsrp_switch_activo }}"

- name: Configurando SWITCH HSRP STANDBY
  hosts: equipos-hsrp-standby-switch
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP STANDBY EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface vlan {{ item.hsrp_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero }} ip {{ item.hsrp_ip_gateway }} 
          - no shutdown     
      loop: "{{ hsrp_switch_standby }}"
        
- name: Configurando ROUTER HSRP ACTIVO
  hosts: equipo-hsrp-activo-router
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP ACTIVO EN EL ROUTER # # # 
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - encapsulation dot1q {{ item.hsrp_numero_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero}} ip {{ item.hsrp_ip_gateway }}
          - standby {{ item.hsrp_numero}} priority {{ item.hsrp_prioridad }}
          - standby {{ item.hsrp_numero}} preempt        
      loop: "{{ hsrp_router_activo }}"

- name: Configurando ROUTER HSRP STANDBY
  hosts: equipos-hsrp-standby-router
  gather_facts: no
  tasks:
    # # # CONFIGURAR HSRP STANDBY EN EL SWITCH # # # 
    - ios_config:
        lines:
          - interface {{ item.hsrp_puerto }}.{{ item.hsrp_numero_vlan }} 
          - encapsulation dot1q {{ item.hsrp_numero_vlan }}
          - ip address {{ item.hsrp_ip_equipo }} {{ item.hsrp_mascara }}
          - standby {{ item.hsrp_numero}} ip {{ item.hsrp_ip_gateway }}      
      loop: "{{ hsrp_router_standby }}"

############################################################################
#     CONFIGURACION DE USUARIOS EN EQUIPOS DE ACUERDO A PARAMETROS EN      # 
#     INVENTORY         !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Creando usuarios en los equipos
  hosts: all
  gather_facts: no 

  tasks:
    - name: Creando usuarios y encriptando passwords
      ios_config:
        lines:
          - username "{{ item.username }}" password "{{ item.password }}"
          - service password-encryption
      loop: "{{ users }}"

############################################################################
#   CONFIGURACION DEL BANNER MOTD EN EQUIPOS DE ACUERDO A PARAMETROS EN    # 
#   INVENTORY           !!!PRECAUCIÓN!!! NO MODIFICAR EL CODIGO            # 
############################################################################

- name: Configuración del login del banner
  hosts: all
  gather_facts: no

  tasks:
    - name: Remover antiguo banner
      ios_banner:
        banner: motd
        state: absent

    - name: Configurando el banner desde un archivo
      ios_banner:
        banner: motd
        text: "{{ lookup('file', './parametros/banner.cfg') }}"
        state: present  

############################################################################
#         BACKUP GENERAL LOCAL DE EQUIPOS EN CARPETA REPOSITORIOS          # 
#                   PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                   # 
############################################################################

- name: Directorios de Repositorios 
  hosts: localhost 
  gather_facts: no
  tasks:
    
    # # # CREACIÓN DEL REPOSITORIO # # #

    # CREACIÓN DEL DIRECTORIO "backup-show-_arp" # 
    - name: Creando la carpeta "backup-show_arp"
      include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_arp
  
    # CREACIÓN DEL DIRECTORIO "backup-show-ip_int_br" #
    - name: Creando la carpeta "backup-show_ip_int_br"
      include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_ip_int_br

    # CREACIÓN DEL DIRECTORIO "backup-show-run" #
    - name: Creando la carpeta "backup-show_run"
      include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: backup-show_run
  
      # CREACIÓN DEL DIRECTORIO "cfg" #
    - name: Creando la carpeta "cfg"
      include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: cfg

    # CREACIÓN DEL DIRECTORIO "detalle-de-equipos" # 
    - name: Creando la carpeta "detalle-de-equipos"
      include_role:
        name: crear_repositorios
      vars: 
        repositorio_nombre_carpeta: detalle-de-equipos

- name: Backup Local
  hosts: all 
  gather_facts: no
  tasks:
  
    # # # GENERACIÓN DE BACKUPS EN DIRECTORIOS # # #

    # BACKUP "show arp" #
    - name: Generando archivos SHOW ARP
      include_role:
        name: backups 
      vars:
        comando_backup: "show arp" 
        backup_nombre_archivo: "arp" 
        backup_nombre_carpeta: backup-show_arp           

    # BACKUP "show ip interface brief" #
    - name: Generando archivos SHOW IP INTERFACE BRIEF 
      include_role:
        name: backups 
      vars:
        comando_backup: "show ip interface brief" 
        backup_nombre_archivo: "ip_int_br" 
        backup_nombre_carpeta: backup-show_ip_int_br     
  
    # BACKUP "show run" #
    - name: Generando archivos SHOW RUN 
      include_role:
        name: backups 
      vars:
        comando_backup: "show run" 
        backup_nombre_archivo: "run" 
        backup_nombre_carpeta: backup-show_run 

    # BACKUP DE EQUIPOS "cfg" #
    - name: Generando archivos ".CFG"
      ios_command:
        commands:
          - show run 
      register: output    
    - name: Grabar la configuracion de los equipos de red
      copy:        
        content: "{{ output.stdout[0] }}"
        dest: ./playbooks/repositorio/{{ nombre_empresa }}/cfg/{{ inventory_hostname }}.cfg

    # BACKUP "detalle de equipos" #
    - name: Obteniendo los parametros de los equipos de red "DETALLE DE EQUIPOS"
      ios_facts:
        gather_subset: all  
    - name: Grabando los parametros de los equipos de red "DETALLE DE EQUIPOS"
      template:
        src: ./template/detalle-de-equipos.j2
        dest: ./playbooks/repositorio/{{ nombre_empresa }}/detalle-de-equipos/detalle-de-equipos.csv

############################################################################
#                           BACKUP A GIT- LAB                              # 
#                   PRECAUCIÓN!!! NO MODIFICAR EL CODIGO                   # 
############################################################################

# BACKUP DE EQUIPOS."CFG" #
- name: BACKUP DE EQUIPOS "cfg"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: ""
        git_ruta: "cfg"
        mensaje_commit: "backup equipos .CFG" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".cfg"
- name: Push GITLAB ".CFG"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab
# BACKUP DE DETALLE DE EQUIPOS #
- name: Push GITLAB "detalle-de-equipos.csv"
  hosts: localhost
  gather_facts: no
  tasks:
    # # # LECTURA DEL CONTENIDO DE LOS ARCHIVOS EN EL INVENTORY # # #
    - name: Lectura del contenido de los archivos txt
      set_fact:
        dir_path: ./repositorio/{{ nombre_empresa }}/detalle-de-equipos/    
        file_content: "{{ item }}"      
      with_file:
        - "./repositorio/{{ nombre_empresa }}/detalle-de-equipos/detalle-de-equipos.csv"      
      no_log: True
    # # # GENERANDO EL ARBOL DE ARCHIVOS DEL REPOSITORIO # # #
    - name: Obtener el árbol de archivos del repositorio
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/tree?ref=master&per_page=100&page=1
        body_format: json
        validate_certs: no  
        status_code: 200
        return_content: yes
        headers:
          Private-Token: "{{ gitlab_access_token }}"
      register: response
      delegate_to: localhost
    # # # OBTENIENDO LOS ARCHIVOS DEL REPOSITORIO # # #
    - name: Obtener los archivos del proyecto
      set_fact:
        project_files: "{{ response.json | json_query('[].name') }}"
        file_name: "detalle-de-equipos.csv"
    # # # ESTABLECIENDO ACCION "CREATE" CUANDO NO EXISTAN ARCHIVOS EN EL PROYECTO # # #
    - name: Establecer la acción de confirmación como "create"
      set_fact:
        commit_action: create
      when: file_name is not in project_files
    # # # ESTABLECIENDO ACCION "UPDATE" CUANDO EXISTAN ARCHIVOS EN EL PROYECTO # # #
    - name: Establecer la acción de confirmación como "update"
      set_fact:
        commit_action: update
      when: file_name in project_files
    # # # OBTENIENDO EL CONTENIDO DE LOS ARCHIVOS EN GITLAB CUANDO LA ACCION SEA "UPDATE" # # #
    - name: Obtener el contenido del archivo de gitlab
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/files/{{ file_name }}/raw?ref=master
        body_format: json
        validate_certs: no
        status_code: 200, 404
        return_content: yes
        headers:
          Private-Token: "{{ gitlab_access_token }}"
      register: response
      delegate_to: localhost
      when: commit_action == "update"
    # # # GRABANDO EL CONTENIDO DE LOS ARCHIVOS EN GITLAB CUANDO LA ACCION SEA "UPDATE" # # #
    - name: Grabando el contenido del archivo de gitlab
      set_fact:
        file_content_in_gitlab: "{{ response.content }}"
      when: commit_action == "update"
    # # # CREANDO EL ACTION DICT CUANDO ESTE "CREATE" O EN "UPDATE" NO HAYA CONTENIDO # # #
    - name: Creando el action dict
      set_fact:
        action_dict:
          action: "{{ commit_action}}"
          file_path: "detalle-de-equipos.csv"
          content: "{{ file_content }}.csv" 
      when: commit_action == "create" or (commit_action == "update" and file_content_in_gitlab != file_content)
    # # # CREANDO EL DICT VACIO CUANDO LA ACCION SEA "UPDATE" Y EXISTA CONTENIDO # # #
    - name: Creando empty dict
      set_fact:
        action_dict: {}
      when: commit_action == "update" and file_content_in_gitlab == file_content
    # # # PUSH A GITLAB CUANDO EL ACTION LIST ESTE DEFINIDO # # #
    - name: Push nuevo/actualizado a gitlab
      uri:
        url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/commits
        headers:
          Private-Token: "{{ gitlab_access_token }}"
        validate_certs: no
        method: POST
        body:
          branch: master
          commit_message: backup detalle-de-equipos.csv 
          actions: 
            - action: "{{ commit_action }}"
              file_path: "detalle-de-equipos.csv"
              content: "{{ file_content }}.csv"            
        status_code: 201
        body_format: json
      delegate_to: localhost

- name: Configuracion PUERTOS ROUTER
  hosts: all
  gather_facts: no
  tasks:
    # # # LLAMADO A ROL GUARDAR CONFIGURACION # # #
    - include_role:
        name: guardar-configuracion