---
- name: Configurar ETHERCHANNEL
  hosts: switch-etherchannel 
  gather_facts: no

  tasks:
     
    - name: Preparando Etherchannel
      ios_config:
        lines:
          - interface port-channel {{ item.etherchannel_numero }}
          - no switchport   
          - ip address {{ item.etherchannel_ip }} {{ item.etherchannel_mascara }}  
      loop: "{{ etherchannel_parametros }}"     
      
     
    - name: Configuracion de interfaces fisicas
      ios_config:
        lines:
          - interface range {{ item.etherchannel_range }}
          - shutdown
          - no switchport 
          - no ip address
          - channel-group {{ item.etherchannel_numero }} mode active
          - no shutdown
      loop: "{{ etherchannel_parametros }}"

    - include_role:
        name: visualizar
      vars: 
        comando_visualizar: "show etherchannel summary"