---
- name: Configurar OSPF
  hosts: router
  gather_facts: no

  tasks:
    - name: Ejecutando el comando "show ospf neighbors"
      ios_command:
        commands: show ip ospf neighbor 
      register: ospf_neighbor

    - name: Visualizar vecinos
      debug:
        var: ospf_neighbor.stdout_lines